version: '3.11'

x-api-build-and-image-local: &api_build_and_image_local
  build:
    dockerfile: Dockerfile
    # noinspection ComposeUnknownKeys
    target: api-php-local
    cache_from:
      - ${DOCKER_IMAGE_PREFIX}/api:local-latest
  image: ${DOCKER_IMAGE_PREFIX}/api:local-latest
  volumes:
    - './src/api:/var/www/html'

services:
  frontend:
    build:
      dockerfile: Dockerfile
      target: frontend-local
      cache_from:
        - ${DOCKER_IMAGE_PREFIX}/frontend:local-latest
    image: ${DOCKER_IMAGE_PREFIX}/frontend:local-latest
    volumes:
      - './src/frontend:/var/www/html'

  juno-satellite:
    image: junobuild/satellite:latest
    ports:
      - 5987:5987
    volumes:
      - juno_satellite:/juno/.juno
      - ./src/frontend/juno.local.json:/juno/juno.dev.json

  api:
    <<: *api_build_and_image_local
    extra_hosts:
      - '${API_EXTRA_HOST:-host.docker.internal}:host-gateway'
    environment:
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}/src/api'
      PHP_IDE_CONFIG: 'serverName=local-docker'
    depends_on:
      pgsql:
        condition: service_healthy
        # noinspection ComposeUnknownKeys
        restart: true
      api-queue:
        condition: service_started
      api-schedule:
        condition: service_started
      mailpit:
        condition: service_started

  api-queue:
    <<: *api_build_and_image_local
    command: php artisan queue:listen
    depends_on:
      - pgsql

  api-schedule:
    <<: *api_build_and_image_local
    command: php artisan schedule:work
    depends_on:
      - pgsql

volumes:
  juno_satellite:
    driver: local
