version: '3.11'

x-api-build-and-image-local: &api_build_and_image_local
  build:
    dockerfile: Dockerfile
    # noinspection ComposeUnknownKeys
    target: api-php-local
    cache_from:
      - ${DOCKER_IMAGE_PREFIX}/api:local-latest
  image: ${DOCKER_IMAGE_PREFIX}/api:local-latest
  volumes:
    - './src/api:/var/www/html'

services:
  api:
    <<: *api_build_and_image_local
    extra_hosts:
      - '${API_EXTRA_HOST:-host.docker.internal}:host-gateway'
    environment:
      XDEBUG_MODE: '${XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}/src/api'
      PHP_IDE_CONFIG: 'serverName=local-docker'
    depends_on:
      mysql:
        condition: service_healthy
        # noinspection ComposeUnknownKeys
        restart: true
      api-queue:
        condition: service_started
      api-schedule:
        condition: service_started
      api-node:
        condition: service_started
      minio-create-bucket:
        condition: service_completed_successfully
      mailpit:
        condition: service_started

  api-queue:
    <<: *api_build_and_image_local
    command: php artisan queue:listen
    depends_on:
      - mysql

  api-schedule:
    <<: *api_build_and_image_local
    command: php artisan schedule:work
    depends_on:
      - mysql

  api-node:
    build:
      dockerfile: Dockerfile
      target: api-node-local
      cache_from:
        - ${DOCKER_IMAGE_PREFIX}/api-node:local-latest
    image: ${DOCKER_IMAGE_PREFIX}/api-node:local-latest
    volumes:
      - './src/api:/var/www/html'
      - './src/langchain/data:/var/www/html/langchain-data'
