version: '3.11'
services:
  api:
    build:
      # noinspection ComposeUnknownKeys
      tags:
        - '${DOCKER_IMAGE_PREFIX}/api:base-${GIT_CURRENT_COMMIT_ID}'

  frontend:
    build:
      # noinspection ComposeUnknownKeys
      tags:
        - '${DOCKER_IMAGE_PREFIX}/frontend:base-${GIT_CURRENT_COMMIT_ID}'
