# syntax=docker/dockerfile:1.4
# /////////////////////////////////////////////////////////////////////
# frontend-base
FROM ubuntu:22.04 as frontend-base

ARG NODE_VERSION=18
ARG CONTAINER_USERNAME=cuser
ARG WWW_DATA_GID=33

LABEL maintainer="Denny Weiß"

ENV DEBIAN_FRONTEND noninteractive \
    && TZ=UTC

RUN useradd -ms /bin/bash --no-user-group -g $WWW_DATA_GID -u 1337 $CONTAINER_USERNAME

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./src/nodesource.gpg /etc/apt/keyrings/nodesource.gpg
COPY ./src/yarn.gpg /etc/apt/keyrings/yarn.gpg

RUN apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
      curl \
      ca-certificates\
      gnupg2 \
      gosu \
      supervisor \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_VERSION.x nodistro main" > /etc/apt/sources.list.d/nodesource.list \
    && echo "deb [signed-by=/etc/apt/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
      nodejs \
      yarn \
    && npm install -g npm \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir /.yarn-cache  \
    && chmod -R ugo+rw /.yarn-cache \
    && chmod -R ugo+rw /tmp

COPY ./src/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY ./src/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

WORKDIR /var/www/html
RUN chown -R www-data:www-data /var/www \
    && chmod -R ug+rwx /var/www

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
EXPOSE 4321

STOPSIGNAL SIGTERM
