# syntax=docker/dockerfile:1.4
# /////////////////////////////////////////////////////////////////////
# api-full-base
FROM ubuntu:22.04 as api-full-base

LABEL maintainer="Denny Weiß"

ARG POSTGRES_VERSION=15
ARG NODE_VERSION=18
ARG CONTAINER_USERNAME=cuser
ARG WWW_DATA_GID=33

LABEL maintainer="Denny Weiß"

ENV DEBIAN_FRONTEND noninteractive \
    TZ=UTC \
    COMPOSER_MAX_PARALLEL_HTTP=24

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN useradd -ms /bin/bash --no-user-group -g $WWW_DATA_GID -u 1337 $CONTAINER_USERNAME

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN mkdir -p /.composer && chmod -R ugo+rw /.composer

COPY ./src/nginx-keyring.gpg /etc/apt/keyrings/nginx-keyring.gpg
COPY ./src/pgdg.gpg /etc/apt/keyrings/pgdg.gpg
COPY ./src/ppa_ondrej_php.gpg /etc/apt/keyrings/ppa_ondrej_php.gpg
ADD ./src/api-base-system-packages.txt /tmp/api-base-system-packages.txt
ADD ./src/api-php8.3-packages.txt /tmp/api-php8.3-packages.txt
COPY ./src/nodesource.gpg /etc/apt/keyrings/nodesource.gpg
COPY ./src/yarn.gpg /etc/apt/keyrings/yarn.gpg

RUN apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
      curl \
      ca-certificates \
      gnupg2 \
    && echo "deb [signed-by=/etc/apt/keyrings/pgdg.gpg] http://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
    && echo "deb [signed-by=/etc/apt/keyrings/ppa_ondrej_php.gpg] https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy main" > /etc/apt/sources.list.d/ppa_ondrej_php.list \
    && echo "deb [signed-by=/etc/apt/keyrings/nginx-keyring.gpg] https://packages.nginx.org/unit/ubuntu/ jammy unit" >> /etc/apt/sources.list.d/unit.list \
    && echo "deb-src [signed-by=/etc/apt/keyrings/nginx-keyring.gpg] https://packages.nginx.org/unit/ubuntu/ jammy unit" >> /etc/apt/sources.list.d/unit.list \
    && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_VERSION.x nodistro main" > /etc/apt/sources.list.d/nodesource.list \
    && echo "deb [signed-by=/etc/apt/keyrings/yarn.gpg] https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y $(cat /tmp/api-base-system-packages.txt) \
    && apt-get install --no-install-recommends --no-install-suggests -y $(cat /tmp/api-php8.3-packages.txt) \
    && apt-get install --no-install-recommends --no-install-suggests -y nodejs yarn \
    && npm install -g npm \
    && apt-get -y autoremove \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./src/php-local.ini /etc/php/8.3/cli/conf.d/99-api.ini
COPY ./src/docker-entrypoint-full.sh /usr/local/bin/docker-entrypoint.sh

RUN mkdir -p /etc/unit/config \
    && mkdir -p /docker-entrypoint.d \
    && setcap "cap_net_bind_service=+ep" /usr/bin/php8.3 \
    && echo "net.core.somaxconn=100000" | tee -a /etc/sysctl.d/99-network-tuning.conf

RUN mkdir /.yarn-cache  \
    && chmod -R ugo+rw /.yarn-cache \
    && chmod -R ugo+rw /tmp

WORKDIR /var/www/html
RUN chown -R www-data:www-data /var/www \
    && chmod -R ug+rwx /var/www

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
EXPOSE 80
EXPOSE 3000
CMD ["unitd", "--no-daemon", "--control", "unix:/var/run/control.unit.sock" ]
